### PR TITLE
Color changing fix

### PR DESCRIPTION
**Pull request by CodeBardian**
fix for #5 and #6. tested on KL-130.

### CODE REVIEW

**Comment by GameDeveloper2017** [comment]
What is an example to change the color of a light on a KL130?

**Comment by CodeBardian** [comment]
Changing color is done through `SetHSV()` method of a bulb. You will need to pass a `BulbHSV` object:
```csharp
BulbHSV red = new BulbHSV { Hue = 0, Saturation = 100, Value = 100}; // red HSV(0°, 100%, 100%)
BulbHSV yellow = new BulbHSV { Hue = 60, Saturation = 100, Value = 100};  // yellow HSV(60°, 100%, 100%)

//apply color
bulb.SetHSV(red);
```

In addition, you can change color to one of the four "preset" light states with `ApplyPreset()` 
```csharp
bulb.ApplyPreset(0);  //changes color to first preset
```

**Comment by GameDeveloper2017** [comment]
> Changing color is done through `SetHSV()` method of a bulb. You will need to pass a `BulbHSV` object:
> 
> ```cs
> BulbHSV red = new BulbHSV { Hue = 0, Saturation = 100, Value = 100}; // red HSV(0°, 100%, 100%)
> BulbHSV yellow = new BulbHSV { Hue = 60, Saturation = 100, Value = 100};  // yellow HSV(60°, 100%, 100%)
> 
> //apply color
> bulb.SetHSV(red);
> ```
> 
> In addition, you can change color to one of the four "preset" light states with `ApplyPreset()`
> 
> ```cs
> bulb.ApplyPreset(0);  //changes color to first preset
> ```

When I add the BulbHSV red = ... and I change by bulb to red, My program hangs and my CPU and RAM usage go to 100

**Comment by GameDeveloper2017** [comment]
is there a reason for that?

**Pull request merged**
